name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.13.0
      uses: actions/setup-node@v1
      with:
        node-version: 10.13.0
    - run: yarn install
    - run: gatsby build
    - run: gatsby serve
      env:
        CI: true
